
resource "local_file" "pet" {
  filename = var.filename
  content  = "My favorite pet is ${random_pet.my-pet.id}"

  depends_on = [
    random_pet.my-pet
  ]
}

resource "random_pet" "my-pet" {
  prefix    = var.prefix
  separator = var.seperator
  length    = var.length
}



output "pet-name" {
  value       = random_pet.my-pet.id
  description = "Record the value of the pet ID generated by the random_pet resource"
}
